// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgtVVVniER1nOXHpBAzyHKI5jm7WRUtkU',
    appId: '1:108710254009:web:a8d01dcae10d454d379268',
    messagingSenderId: '108710254009',
    projectId: 'gigly-2927a',
    authDomain: 'gigly-2927a.firebaseapp.com',
    storageBucket: 'gigly-2927a.firebasestorage.app',
    measurementId: 'G-QQTGE6E8K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3CuDgSbVbJdA-Q216FyvDImdj0wMkog',
    appId: '1:108710254009:android:6cd3454973c94408379268',
    messagingSenderId: '108710254009',
    projectId: 'gigly-2927a',
    storageBucket: 'gigly-2927a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR5YkZ6HWXEajXARcckSd_08epGWC6zxw',
    appId: '1:108710254009:ios:dc9876ecdfef1f27379268',
    messagingSenderId: '108710254009',
    projectId: 'gigly-2927a',
    storageBucket: 'gigly-2927a.firebasestorage.app',
    iosClientId: '108710254009-d1gv657n8oik4vfac9g9256bg67lnljr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR5YkZ6HWXEajXARcckSd_08epGWC6zxw',
    appId: '1:108710254009:ios:dc9876ecdfef1f27379268',
    messagingSenderId: '108710254009',
    projectId: 'gigly-2927a',
    storageBucket: 'gigly-2927a.firebasestorage.app',
    iosClientId: '108710254009-d1gv657n8oik4vfac9g9256bg67lnljr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gigly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgtVVVniER1nOXHpBAzyHKI5jm7WRUtkU',
    appId: '1:108710254009:web:34f69dc797994255379268',
    messagingSenderId: '108710254009',
    projectId: 'gigly-2927a',
    authDomain: 'gigly-2927a.firebaseapp.com',
    storageBucket: 'gigly-2927a.firebasestorage.app',
    measurementId: 'G-WLC9ZF32KH',
  );
}
